# GitHub Actions Workflow for CI/CD
name: "Build and Deploy"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v12
      with:
        name: homelab-cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Check flake
      run: nix flake check

    - name: Build all configurations
      run: |
        nix build .#nixosConfigurations.arm-control.config.system.build.toplevel
        nix build .#nixosConfigurations.slave-01.config.system.build.toplevel
        nix build .#nixosConfigurations.slave-02.config.system.build.toplevel

  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to control node
      run: |
        # Add known hosts
        ssh-keyscan -H ${{ secrets.CONTROL_NODE_HOST }} >> ~/.ssh/known_hosts
        
        # Deploy
        nixos-rebuild switch --flake .#arm-control --target-host root@${{ secrets.CONTROL_NODE_HOST }}

    - name: Notify deployment
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#homelab'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        message: |
          Deployment ${{ job.status }}
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }}
          Commit: ${{ github.sha }}